function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

CreateThread(function()
	AddTextEntry("tr_pdchar2spoil_1", "[TR] Prim Spoiler")
	AddTextEntry("tr_pdchar2spoil_2", "[TR] Second Spoiler")
	AddTextEntry("tr_pdchar2spoil_3", "[TR] Carbon Spoiler")
	AddTextEntry("tr_pdchar2roof_1", "[TR] Secondary Roof")
	AddTextEntry("tr_pdchar2roof_2", "[TR] Carbon Roof")
	AddTextEntry("tr_pdchar2_null_1", "[TR] Secondary Mirror")
	AddTextEntry("tr_pdchar2_null_2", "[TR] Carbon Mirror")
	AddTextEntry("tr_pdchar2_hood_1", "[TR] Secondary Hood")
	AddTextEntry("tr_pdchar2_hood_2", "[TR] Carbon Hood")
	AddTextEntry("tr_pdchar2_null_4", "[TR] Prim Door Color")
	AddTextEntry("tr_pdchar2_gunrack", "[TR] Gun Rack Only")
	AddTextEntry("tr_pdchar2_divider_1a", "[TR] Gun Rack / Divider")
	AddTextEntry("tr_pdchar2_divider_2a", "[TR] Gun Rack / Divider Cam")
	AddTextEntry("tr_pdchar2_divider_1b", "[TR]Gun Rack / Divider Open")
	AddTextEntry("tr_pdchar2_divider_2b", "[TR] Gun Rack / Divider Cam")
	AddTextEntry("tr_pdchar2_rambar", "[TR] Rambar")
    AddTextEntry("tr_pdchar2_csign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar2_csign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar2_csign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar2_csign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar2_csign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar2_csign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar2_csign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar2_csign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar2_csign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar2_csign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar2_csign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar2_csign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar2_csign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar2_csign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar2_csign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar2_csign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar2_csign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar2_csign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar2_csign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar2_csign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar2_csign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar2_csign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar2_csign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar2_csign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar2_csign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar2_csign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar2_csign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar2_csign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar2_csign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar2_csign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar2_csign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar2_csign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar2_csign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar2_csign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar2_csign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar2_csign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar2_csign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar2_csign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar2_csign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar2_csign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar2_csign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar2_csign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar2_csign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar2_csign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar2_csign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar2_csign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar2_csign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar2_csign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar2_csign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar2_csign_e9", "[TR] CallSign 9")
	AddTextEntry("tr_pdchar2_livery1", "[TR] LSPD livery")
	AddTextEntry("tr_pdchar2_livery2", "[TR] BSCO livery")
	AddTextEntry("tr_pdchar2_livery3", "[TR] SAPR livery")
	AddTextEntry("tr_pdchar2_livery4", "[TR] State livery")
	AddTextEntry("tr_pdchar2_doorrank_1", "[TR] Supervisor Rank")
	AddTextEntry("tr_pdchar2_doorrank_2", "[TR] Command Rank")
	AddTextEntry("tr_pdchar2_doorrank_2", "[TR] Command Rank")
	AddTextEntry("tr_pdchar2_ant_a1", "[TR] State Range")
	AddTextEntry("tr_pdchar2_ant_b1", "[TR] BSCO/LSPD Range")
end)
