function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry("tr_pddurango_flag_1", "[TR] USA Flag")
    AddTextEntry("tr_pddurango_flag_2", "[TR] AU Flag")
    AddTextEntry("tr_pddurango_flag_3", "[TR] Brazil Flag")
    AddTextEntry("tr_pddurango_flag_4", "[TR] Spain Flag")
    AddTextEntry("tr_pddurango_flag_5", "[TR] canada Flag")
    AddTextEntry("tr_pddurango_flag_6", "[TR] France Flag")
    AddTextEntry("tr_pddurango_flag_7", "[TR] Germany Flag")
    AddTextEntry("tr_pddurango_flag_8", "[TR] Japan Flag")
    AddTextEntry("tr_pddurango_flag_9", "[TR] Scotland Flag")
    AddTextEntry("tr_pddurango_flag_10", "[TR] UK Flag")
    AddTextEntry("tr_pddurango_flag_11", "[TR] Italy Flag")
    AddTextEntry("tr_pddurango_flag_12", "[TR] Switzerland Flag")
    AddTextEntry("tr_pddurango_flag_13", "[TR] Jamaica Flag")
    AddTextEntry("tr_pddurango_flag_14", "[TR] Colombia Flag")
    AddTextEntry("tr_pddurango_flag_15", "[TR] Norway Flag")
    AddTextEntry("tr_pddurango_flag_16", "[TR] Sweden Flag")
    AddTextEntry("tr_pddurango_flag_17", "[TR] Belgium Flag")
    AddTextEntry("tr_pddurango_flag_18", "[TR] Mexico Flag")
    AddTextEntry("tr_pddurango_flag_19", "[TR] S. Africa Flag")
    AddTextEntry("tr_pddurango_flag_20", "[TR] Russia Flag")
    AddTextEntry("tr_pddurango_flag_21", "[TR] Argentina Flag")
    AddTextEntry("tr_pddurango_flag_22", "[TR] Turkey Flag")
    AddTextEntry("tr_pddurango_flag_23", "[TR] Ireland Flag")
    AddTextEntry("tr_pddurango_flag_24", "[TR] Wales Flag")
    AddTextEntry("tr_pddurango_flag_25", "[TR] England Flag")
    AddTextEntry("tr_pddurango_ram_1a", "[TR] RamBar")
    AddTextEntry("tr_pddurango_ram_2a", "[TR] RamBar / Wrap Around")
    AddTextEntry("tr_pddurango_divider_1a", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pddurango_divider_2a", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pddurango_divider_1b", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pddurango_divider_2b", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pddurango_callsign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pddurango_callsign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pddurango_callsign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pddurango_callsign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pddurango_callsign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pddurango_callsign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pddurango_callsign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pddurango_callsign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pddurango_callsign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pddurango_callsign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pddurango_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pddurango_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pddurango_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pddurango_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pddurango_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pddurango_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pddurango_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pddurango_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pddurango_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pddurango_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pddurango_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pddurango_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pddurango_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pddurango_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pddurango_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pddurango_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pddurango_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pddurango_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pddurango_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pddurango_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pddurango_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pddurango_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pddurango_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pddurango_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pddurango_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pddurango_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pddurango_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pddurango_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pddurango_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pddurango_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pddurango_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pddurango_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pddurango_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pddurango_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pddurango_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pddurango_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pddurango_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pddurango_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pddurango_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pddurango_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_pddurango_badge_rear", "[TR] SRU Badges")
    AddTextEntry("tr_pddurango_ant_1a", "[TR] State Range")
    AddTextEntry("tr_pddurango_livery_1", "[TR] LSPD Livery")
    AddTextEntry("tr_pddurango_livery_2", "[TR] Sheriff Livery")
    AddTextEntry("tr_pddurango_livery_3", "[TR] State Livery")
    AddTextEntry("tr_pddurango_livery_4", "[TR] Park Ranger Livery")
    AddTextEntry("tr_pddurango_livery_5", "[TR] SRU Livery")
    AddTextEntry("rank1", "[TR] Supv")
    AddTextEntry("rank2", "[TR] Command.")
    AddTextEntry("tr_pddurango_radar", "[TR] Radar.")
    AddTextEntry("tr_pddurango_srt", "[TR] SRU Kit.")
end)
