function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry("tr_pdmstang_csign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdmstang_csign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdmstang_csign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdmstang_csign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdmstang_csign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdmstang_csign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdmstang_csign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdmstang_csign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdmstang_csign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdmstang_csign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdmstang_csign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdmstang_csign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdmstang_csign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdmstang_csign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdmstang_csign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdmstang_csign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdmstang_csign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdmstang_csign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdmstang_csign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdmstang_csign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdmstang_csign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdmstang_csign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdmstang_csign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdmstang_csign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdmstang_csign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdmstang_csign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdmstang_csign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdmstang_csign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdmstang_csign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdmstang_csign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdmstang_spol_1", "[TR] GT Spoiler")
    AddTextEntry("tr_pdmstang_spol_2", "[TR] 2019 Spoiler")
    AddTextEntry("tr_pdmstang_spol_3", "[TR] 19 Spoiler / Lip")
    AddTextEntry("tr_pdmstang_spol_4", "[TR] Duck Spoiler")
    AddTextEntry("tr_pdmstang_spol_5", "[TR] Sports Spoiler")
    AddTextEntry("tr_pdmstang_spol_6", "[TR] Roush Spoiler")
    AddTextEntry("tr_pdmstang_bumf_1", "[TR] RTR Bumper")
    AddTextEntry("tr_pdmstang_bumf_2", "[TR] HALO Stang")
    AddTextEntry("tr_pdmstang_bumf_3", "[TR] HALO RTR Stang")
    AddTextEntry("tr_pdmstang_bumr_1", "[TR] RTR Bumper")
    AddTextEntry("tr_pdmstang_bumr_2", "[TR] 5.0 Arch Bumper")
    AddTextEntry("tr_pdmstang_rollcage", "[TR] Roll Cage")
    AddTextEntry("tr_pdmstang_divider_1a", "[TR] Divider / Gun")
    AddTextEntry("tr_pdmstang_divider_2a", "[TR] Divider / Cam")
    AddTextEntry("tr_pdmstang_divider_1b", "[TR] Open Divider")
    AddTextEntry("tr_pdmstang_divider_2b", "[TR] Open w/ Cam")
    AddTextEntry("tr_pdmstang_ram_1a", "[TR] State Ram Bar")
    AddTextEntry("tr_pdmstang_bon_1", "[TR] RTR Hood")
    AddTextEntry("tr_pdmstang_bon_2", "[TR] Roush Hood")
    AddTextEntry("tr_pdmstang_roof_1", "[TR] Black Roof")
    AddTextEntry("tr_pdmstang_roof_2", "[TR] Black Roof / Nip")
    AddTextEntry("tr_pdmstang_roof_3", "[TR] All Black")
    AddTextEntry("tr_pdmstang_antenna_1a", "[TR] State Range Antenna")
    AddTextEntry("tr_pdmstang_antenna_1a2", "[TR] Local Antenna")
    AddTextEntry("tr_pdmstang_antenna_1b", "[TR] City Antenna")
    AddTextEntry("tr_pdmstang_badge_a", "[TR] Roush Badge")
    AddTextEntry("tr_pdmstang_badge_b", "[TR] RTR Badge")
    AddTextEntry("tr_pdmstang_scoop", "[TR] GT Scoop")
    AddTextEntry("tr_pdmstang_livery1", "[TR] POLICE Livery")
    AddTextEntry("tr_pdmstang_livery2", "[TR] BSCO Livery")
    AddTextEntry("tr_pdmstang_livery3", "[TR] STATE Livery")
    AddTextEntry("tr_pdmstang_livery4", "[TR] RANGER Livery")
    AddTextEntry("tr_pdmstang_livery5", "[TR] SRU Livery")
    AddTextEntry("tr_pdmstang_livery6", "[TR] SWAT Livery")
end)
