function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry("tr_pdvic_callsign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdvic_callsign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdvic_callsign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdvic_callsign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdvic_callsign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdvic_callsign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdvic_callsign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdvic_callsign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdvic_callsign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdvic_callsign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdvic_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdvic_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdvic_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdvic_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdvic_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdvic_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdvic_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdvic_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdvic_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdvic_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdvic_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdvic_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdvic_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdvic_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdvic_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdvic_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdvic_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdvic_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdvic_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdvic_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdvic_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pdvic_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pdvic_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pdvic_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pdvic_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pdvic_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pdvic_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pdvic_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pdvic_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pdvic_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pdvic_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pdvic_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pdvic_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pdvic_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pdvic_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pdvic_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pdvic_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pdvic_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pdvic_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pdvic_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_pdvic_antenna_1a", "[TR] LSPD City Range")
    AddTextEntry("tr_pdvic_antenna_1a_2", "[TR] BSCO County Range")
    AddTextEntry("tr_pdvic_antenna_1a_3", "[TR] State Range Antenna")
    AddTextEntry("tr_pdvic_bikerack", "[TR] Bike Rack")
    AddTextEntry("tr_pdvic_divider_1a", "[TR] Divider / Gun")
    AddTextEntry("tr_pdvic_divider_2a", "[TR] Divider / Cam")
    AddTextEntry("tr_pdvic_divider_1b", "[TR] Open Divider")
    AddTextEntry("tr_pdvic_divider_2b", "[TR] Open w/ Cam")
    AddTextEntry("tr_pdvic_k9_a", "[TR] K9 / Dog Rug 1")
    AddTextEntry("tr_pdvic_k9_b", "[TR] K9 / Dog Rug 2")
    AddTextEntry("tr_pdvic_k9_c", "[TR] K9 / Dog Rug 3")
    AddTextEntry("tr_pdvic_k9_d", "[TR] K9 / Support The Blue")
    AddTextEntry("tr_pdvic_livery1", "[TR] LSPD Livery")
    AddTextEntry("tr_pdvic_livery2", "[TR] LSPD w/K9 Livery")
    AddTextEntry("tr_pdvic_livery3", "[TR] BSCO Livery")
    AddTextEntry("tr_pdvic_livery4", "[TR] BSCO w/K9 Livery")
    AddTextEntry("tr_pdvic_livery5", "[TR] State Livery")
    AddTextEntry("tr_pdvic_livery6", "[TR] State w/K9 Livery")
    AddTextEntry("tr_pdvic_livery7", "[TR] Ranger Livery")
    AddTextEntry("tr_pdvic_livery8", "[TR] Ranger w/K9 Livery")
    AddTextEntry("tr_pdvic_livery9", "[TR] DOC Livery")
    AddTextEntry("tr_pdvic_livery10", "[TR] Swat Livery")
    AddTextEntry("tr_pdvic_rank1", "[TR] Command Rank")
    AddTextEntry("tr_pdvic_rank2", "[TR] Supv. Rank")
    AddTextEntry("tr_pdvic_sticker_001", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_002", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_003", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_004", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_005", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_006", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_007", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_008", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_009", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_010", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_011", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_012", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_013", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_014", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_015", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_100", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_101", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_102", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_200", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_201", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_202", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_203", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_204", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_205", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_206", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_207", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_208", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_209", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_210", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_211", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_212", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_213", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_214", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_215", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_216", "[TR] Sticker")
    AddTextEntry("tr_pdvic_trunk_1a", "[TR] Medical Bag")
    AddTextEntry("tr_pdvic_trunk_2a", "[TR] Police Gear")
    AddTextEntry("tr_pdvic_ram_1a", "[TR] LSPD Rambar")
    AddTextEntry("tr_pdvic_ram_1b", "[TR] BSCO/State Rambar")
    AddTextEntry("tr_pdvic_ram_2b", "[TR] Rangers Rambar")
end)
