function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()

    -- TR Dodge Demon (Police)
    AddTextEntry("tr_pddm_csign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pddm_csign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pddm_csign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pddm_csign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pddm_csign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pddm_csign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pddm_csign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pddm_csign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pddm_csign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pddm_csign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pddm_csign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pddm_csign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pddm_csign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pddm_csign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pddm_csign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pddm_csign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pddm_csign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pddm_csign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pddm_csign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pddm_csign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pddm_csign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pddm_csign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pddm_csign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pddm_csign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pddm_csign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pddm_csign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pddm_csign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pddm_csign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pddm_csign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pddm_csign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pddm_csign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pddm_csign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pddm_csign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pddm_csign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pddm_csign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pddm_csign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pddm_csign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pddm_csign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pddm_csign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pddm_csign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pddm_csign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pddm_csign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pddm_csign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pddm_csign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pddm_csign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pddm_csign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pddm_csign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pddm_csign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pddm_csign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pddm_csign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_pddm_livery1", "[TR] Police Livery")
    AddTextEntry("tr_pddm_livery2", "[TR] Sheriff Livery")
    AddTextEntry("tr_pddm_livery3", "[TR] State Livery")
    AddTextEntry("tr_pddm_livery4", "[TR] Ranger Livery")
    AddTextEntry("tr_pddm_livery5", "[TR] SRU Livery")
    AddTextEntry("tr_pddm_livery6", "[TR] Swat Livery")
    AddTextEntry("tr_pddm_rollcage", "[TR] Roll Cage")
    AddTextEntry("tr_pddm_ram_1a", "[TR] Rambar")
    AddTextEntry("tr_pddm_antenna_1a", "[TR] State Range Antenna")
    AddTextEntry("tr_pddm_antenna_1b", "[TR] Local Range Antenna")
    AddTextEntry("tr_pddm_antenna_1c", "[TR] City Range Antenna")
    AddTextEntry("tr_pddm_roof", "[TR] All Black Roof")

    -- TR Corvette (Police)
	AddTextEntry("tr_pdcv_rollcage", "[TR] Roll Cage")
	AddTextEntry("tr_pdcv_zr1badge", "[TR] Hood Badge")
	AddTextEntry("tr_pdcv_zr1skits", "[TR] Skirt Kit")
	AddTextEntry("tr_pdcv_spoiler_1", "[TR] Duck Spoiler Raised")
	AddTextEntry("tr_pdcv_spoiler_2", "[TR] Duck Spoiler Raised/Bolts")
	AddTextEntry("tr_pdcv_spoiler_3", "[TR] Duck Sport Spoiler")
    AddTextEntry("tr_pdcv_riflemount_1", "[TR] Empty Rack")
    AddTextEntry("tr_pdcv_riflemount_2", "[TR] M4A1")
    AddTextEntry("tr_pdcv_riflemount_3", "[TR] M4A1 / SHOTGUN")
    AddTextEntry("tr_pdcv_riflemount_4", "[TR] SHOTGUN")
    AddTextEntry("tr_pdcv_sticker_1", "[TR] Sticker 1")
    AddTextEntry("tr_pdcv_sticker_2", "[TR] Sticker 2")
    AddTextEntry("tr_pdcv_sticker_3", "[TR] Sticker 3")
    AddTextEntry("tr_pdcv_sticker_4", "[TR] Sticker 4")
    AddTextEntry("tr_pdcv_sticker_5", "[TR] Sticker 5")
    AddTextEntry("tr_pdcv_sticker_6", "[TR] Sticker 6")
    AddTextEntry("tr_pdcv_sticker_7", "[TR] Sticker 7")
    AddTextEntry("tr_pdcv_sticker_8", "[TR] Sticker 8")
    AddTextEntry("tr_pdcv_csign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdcv_csign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdcv_csign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdcv_csign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdcv_csign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdcv_csign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdcv_csign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdcv_csign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdcv_csign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdcv_csign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdcv_csign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdcv_csign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdcv_csign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdcv_csign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdcv_csign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdcv_csign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdcv_csign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdcv_csign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdcv_csign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdcv_csign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdcv_csign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdcv_csign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdcv_csign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdcv_csign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdcv_csign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdcv_csign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdcv_csign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdcv_csign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdcv_csign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdcv_csign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdcv_livery1", "[TR] Police Livery")
    AddTextEntry("tr_pdcv_livery2", "[TR] Sheriff Livery")
    AddTextEntry("tr_pdcv_livery3", "[TR] State Livery")
    AddTextEntry("tr_pdcv_livery4", "[TR] Ranger Livery")
    AddTextEntry("tr_pdcv_livery5", "[TR] SRU Livery")
    AddTextEntry("tr_pdcv_livery6", "[TR] Swat Livery")
    AddTextEntry("tr_pdcv_antenna_1a", "[TR] State Range Antenna")

    -- TR Mustang (Police)
    AddTextEntry("tr_pdmstang_csign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdmstang_csign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdmstang_csign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdmstang_csign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdmstang_csign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdmstang_csign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdmstang_csign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdmstang_csign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdmstang_csign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdmstang_csign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdmstang_csign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdmstang_csign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdmstang_csign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdmstang_csign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdmstang_csign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdmstang_csign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdmstang_csign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdmstang_csign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdmstang_csign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdmstang_csign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdmstang_csign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdmstang_csign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdmstang_csign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdmstang_csign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdmstang_csign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdmstang_csign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdmstang_csign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdmstang_csign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdmstang_csign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdmstang_csign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdmstang_spol_1", "[TR] GT Spoiler")
    AddTextEntry("tr_pdmstang_spol_2", "[TR] 2019 Spoiler")
    AddTextEntry("tr_pdmstang_spol_3", "[TR] 19 Spoiler / Lip")
    AddTextEntry("tr_pdmstang_spol_4", "[TR] Duck Spoiler")
    AddTextEntry("tr_pdmstang_spol_5", "[TR] Sports Spoiler")
    AddTextEntry("tr_pdmstang_spol_6", "[TR] Roush Spoiler")
    AddTextEntry("tr_pdmstang_bumf_1", "[TR] RTR Bumper")
    AddTextEntry("tr_pdmstang_bumf_2", "[TR] HALO Stang")
    AddTextEntry("tr_pdmstang_bumf_3", "[TR] HALO RTR Stang")
    AddTextEntry("tr_pdmstang_bumr_1", "[TR] RTR Bumper")
    AddTextEntry("tr_pdmstang_bumr_2", "[TR] 5.0 Arch Bumper")
    AddTextEntry("tr_pdmstang_rollcage", "[TR] Roll Cage")
    AddTextEntry("tr_pdmstang_divider_1a", "[TR] Divider / Gun")
    AddTextEntry("tr_pdmstang_divider_2a", "[TR] Divider / Cam")
    AddTextEntry("tr_pdmstang_divider_1b", "[TR] Open Divider")
    AddTextEntry("tr_pdmstang_divider_2b", "[TR] Open w/ Cam")
    AddTextEntry("tr_pdmstang_ram_1a", "[TR] State Ram Bar")
    AddTextEntry("tr_pdmstang_bon_1", "[TR] RTR Hood")
    AddTextEntry("tr_pdmstang_bon_2", "[TR] Roush Hood")
    AddTextEntry("tr_pdmstang_roof_1", "[TR] Black Roof")
    AddTextEntry("tr_pdmstang_roof_2", "[TR] Black Roof / Nip")
    AddTextEntry("tr_pdmstang_roof_3", "[TR] All Black")
    AddTextEntry("tr_pdmstang_antenna_1a", "[TR] State Range Antenna")
    AddTextEntry("tr_pdmstang_antenna_1a2", "[TR] Local Antenna")
    AddTextEntry("tr_pdmstang_antenna_1b", "[TR] City Antenna")
    AddTextEntry("tr_pdmstang_badge_a", "[TR] Roush Badge")
    AddTextEntry("tr_pdmstang_badge_b", "[TR] RTR Badge")
    AddTextEntry("tr_pdmstang_scoop", "[TR] GT Scoop")
    AddTextEntry("tr_pdmstang_livery1", "[TR] POLICE Livery")
    AddTextEntry("tr_pdmstang_livery2", "[TR] BSCO Livery")
    AddTextEntry("tr_pdmstang_livery3", "[TR] STATE Livery")
    AddTextEntry("tr_pdmstang_livery4", "[TR] RANGER Livery")
    AddTextEntry("tr_pdmstang_livery5", "[TR] SRU Livery")
    AddTextEntry("tr_pdmstang_livery6", "[TR] SWAT Livery")

    -- TR Civ Mustang (Civ)
    AddTextEntry("tr_19civmustang_spol_1", "[TR] GT Spoiler")
    AddTextEntry("tr_19civmustang_spol_2", "[TR] 2019 Spoiler")
    AddTextEntry("tr_19civmustang_spol_3", "[TR] 19 Spoiler / Lip")
    AddTextEntry("tr_19civmustang_spol_4", "[TR] Duck Spoiler")
    AddTextEntry("tr_19civmustang_spol_5", "[TR] Sports Spoiler")
    AddTextEntry("tr_19civmustang_spol_6", "[TR] Roush Spoiler")
    AddTextEntry("tr_19civmustang_bumf_1", "[TR] RTR Bumper")
    AddTextEntry("tr_19civmustang_bumf_2", "[TR] HALO Stang")
    AddTextEntry("tr_19civmustang_bumf_3", "[TR] HALO RTR Stang")
    AddTextEntry("tr_19civmustang_bumr_1", "[TR] RTR Bumper")
    AddTextEntry("tr_19civmustang_bumr_2", "[TR] 5.0 Arch Bumper")
    AddTextEntry("tr_19civmustang_rollcage", "[TR] Roll Cage")
    AddTextEntry("tr_19civmustang_bon_1", "[TR] RTR Hood")
    AddTextEntry("tr_19civmustang_bon_2", "[TR] Roush Hood")
    AddTextEntry("tr_19civmustang_roof_1", "[TR] Black Roof")
    AddTextEntry("tr_19civmustang_roof_2", "[TR] Black Roof / Nip")
    AddTextEntry("tr_19civmustang_roof_3", "[TR] All Black")
    AddTextEntry("tr_19civmustang_badge_a", "[TR] Roush Badge")
    AddTextEntry("tr_19civmustang_badge_b", "[TR] RTR Badge")
    AddTextEntry("tr_19civmustang_scoop", "[TR] GT Scoop")
    AddTextEntry("tr_19civmustang_livery1", "[TR] Vocaloid Livery")
    AddTextEntry("tr_19civmustang_livery2", "[TR] Hot Wheel Livery")
    AddTextEntry("tr_19civmustang_livery3", "[TR] Pattern Livery")
    AddTextEntry("tr_19civmustang_livery4", "[TR] Japenesse Livery")
    AddTextEntry("tr_19civmustang_livery5", "[TR] Red Racing Strips Livery")
    AddTextEntry("tr_19civmustang_livery6", "[TR] NFFA Livery")

    -- TR Crown Vic (Police)
    AddTextEntry("tr_pdvic_callsign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdvic_callsign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdvic_callsign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdvic_callsign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdvic_callsign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdvic_callsign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdvic_callsign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdvic_callsign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdvic_callsign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdvic_callsign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdvic_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdvic_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdvic_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdvic_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdvic_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdvic_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdvic_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdvic_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdvic_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdvic_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdvic_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdvic_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdvic_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdvic_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdvic_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdvic_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdvic_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdvic_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdvic_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdvic_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdvic_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pdvic_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pdvic_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pdvic_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pdvic_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pdvic_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pdvic_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pdvic_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pdvic_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pdvic_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pdvic_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pdvic_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pdvic_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pdvic_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pdvic_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pdvic_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pdvic_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pdvic_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pdvic_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pdvic_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_pdvic_antenna_1a", "[TR] LSPD City Range")
    AddTextEntry("tr_pdvic_antenna_1a_2", "[TR] BSCO County Range")
    AddTextEntry("tr_pdvic_antenna_1a_3", "[TR] State Range Antenna")
    AddTextEntry("tr_pdvic_bikerack", "[TR] Bike Rack")
    AddTextEntry("tr_pdvic_divider_1a", "[TR] Divider / Gun")
    AddTextEntry("tr_pdvic_divider_2a", "[TR] Divider / Cam")
    AddTextEntry("tr_pdvic_divider_1b", "[TR] Open Divider")
    AddTextEntry("tr_pdvic_divider_2b", "[TR] Open w/ Cam")
    AddTextEntry("tr_pdvic_k9_a", "[TR] K9 / Dog Rug 1")
    AddTextEntry("tr_pdvic_k9_b", "[TR] K9 / Dog Rug 2")
    AddTextEntry("tr_pdvic_k9_c", "[TR] K9 / Dog Rug 3")
    AddTextEntry("tr_pdvic_k9_d", "[TR] K9 / Support The Blue")
    AddTextEntry("tr_pdvic_livery1", "[TR] LSPD Livery")
    AddTextEntry("tr_pdvic_livery2", "[TR] LSPD w/K9 Livery")
    AddTextEntry("tr_pdvic_livery3", "[TR] BSCO Livery")
    AddTextEntry("tr_pdvic_livery4", "[TR] BSCO w/K9 Livery")
    AddTextEntry("tr_pdvic_livery5", "[TR] State Livery")
    AddTextEntry("tr_pdvic_livery6", "[TR] State w/K9 Livery")
    AddTextEntry("tr_pdvic_livery7", "[TR] Ranger Livery")
    AddTextEntry("tr_pdvic_livery8", "[TR] Ranger w/K9 Livery")
    AddTextEntry("tr_pdvic_livery9", "[TR] DOC Livery")
    AddTextEntry("tr_pdvic_livery10", "[TR] Swat Livery")
    AddTextEntry("tr_pdvic_rank1", "[TR] Command Rank")
    AddTextEntry("tr_pdvic_rank2", "[TR] Supv. Rank")
    AddTextEntry("tr_pdvic_sticker_001", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_002", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_003", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_004", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_005", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_006", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_007", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_008", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_009", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_010", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_011", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_012", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_013", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_014", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_015", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_100", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_101", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_102", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_200", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_201", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_202", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_203", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_204", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_205", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_206", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_207", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_208", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_209", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_210", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_211", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_212", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_213", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_214", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_215", "[TR] Sticker")
    AddTextEntry("tr_pdvic_sticker_216", "[TR] Sticker")
    AddTextEntry("tr_pdvic_trunk_1a", "[TR] Medical Bag")
    AddTextEntry("tr_pdvic_trunk_2a", "[TR] Police Gear")
    AddTextEntry("tr_pdvic_ram_1a", "[TR] LSPD Rambar")
    AddTextEntry("tr_pdvic_ram_1b", "[TR] BSCO/State Rambar")
    AddTextEntry("tr_pdvic_ram_2b", "[TR] Rangers Rambar")

    --Charger PD / Widebody
    AddTextEntry("tr_pdchar_perform", "[TR] Performance Package")
    AddTextEntry("tr_pdchar_spoiler_1", "[TR] SRT Spoiler (SGT)")
    AddTextEntry("tr_pdchar_spoiler_2", "[TR] Hellcat")
    AddTextEntry("tr_pdchar_spoiler_3", "[TR] Hellcat Spoiler (SRU Leaders)")
    AddTextEntry("tr_pdchar_rearbadge", "[TR] SRU Badges (Non-WideBody)")
    AddTextEntry("tr_pdchar_trunk_a1", "[TR] Gun Case")
    AddTextEntry("tr_pdchar_trunk_b1", "[TR] Gun Case w/Magz")
    AddTextEntry("tr_pdchar_trunk_b2", "[TR] Gun Case w/ Fire Ext.")
    AddTextEntry("tr_pdchar_trunk_c1", "[TR] Full Trunk")
    AddTextEntry("tr_pdchar_trunk_c2", "[TR] Full Trunk 2")
    AddTextEntry("tr_pdchar_convar", "[TR] WideBody for Hellcat Conversion (SRU Leaders)")
    AddTextEntry("tr_pdchar_divider_1a", "[TR] Divider w/gun")
    AddTextEntry("tr_pdchar_divider_2a", "[TR] Divider w/gun & Cam")
    AddTextEntry("tr_pdchar_divider_1b", "[TR] Divider Open w/gun")
    AddTextEntry("tr_pdchar_divider_2b", "[TR] Divider Open w/gun & Cam")
    AddTextEntry("tr_pdchar_rank1", "[TR] Command")
    AddTextEntry("tr_pdchar_rank2", "[TR] Supv.")
    AddTextEntry("tr_pdchar_ram_1a", "[TR] RamBar")
    AddTextEntry("tr_pdchar_callsign_a0", "[TR] RamBar")
    AddTextEntry("tr_pdchar_callsign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar_callsign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar_callsign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar_callsign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar_callsign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar_callsign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar_callsign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar_callsign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar_callsign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar_callsign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar_ant_1a_v1", "[TR] Local PD")
    AddTextEntry("tr_pdchar_ant_1a_v2", "[TR] BSCO")
    AddTextEntry("tr_pdchar_ant_1b", "[TR] State")
    AddTextEntry("tr_pdchar_livery1", "[TR] LSPD Livery")
    AddTextEntry("tr_pdchar_livery2", "[TR] BSCO Livery")
    AddTextEntry("tr_pdchar_livery3", "[TR] State Livery")
    AddTextEntry("tr_pdchar_livery4", "[TR] Ranger Livery")
    AddTextEntry("tr_pdchar_livery5", "[TR] SRU Livery")
    AddTextEntry("sru_wheel_widebody", "[TR] SRU Widebody Wheel")
    AddTextEntry("sru_wheel_non_widebody", "[TR] Sru Wheel Non-Widebody")

    -- 2020 Exp

    AddTextEntry("tr_pdexpse_1a", "[TR] Back Seats")
    AddTextEntry("tr_pdexp_k9_1a", "[TR] K9 Back Full")
    AddTextEntry("tr_pdexp_k9_1b", "[TR] K9 Back Half")
    AddTextEntry("tr_pdexp_bars_1a", "[TR] Window Bars")
    AddTextEntry("tr_pdexp_flag_01", "[TR] USA Flag")
    AddTextEntry("tr_pdexp_flag_02", "[TR] AU Flag")
    AddTextEntry("tr_pdexp_flag_03", "[TR] Brazil Flag")
    AddTextEntry("tr_pdexp_flag_04", "[TR] Spain Flag")
    AddTextEntry("tr_pdexp_flag_05", "[TR] canada Flag")
    AddTextEntry("tr_pdexp_flag_06", "[TR] France Flag")
    AddTextEntry("tr_pdexp_flag_07", "[TR] Germany Flag")
    AddTextEntry("tr_pdexp_flag_08", "[TR] Japan Flag")
    AddTextEntry("tr_pdexp_flag_09", "[TR] Scotland Flag")
    AddTextEntry("tr_pdexp_flag_10", "[TR] UK Flag")
    AddTextEntry("tr_pdexp_flag_11", "[TR] Italy Flag")
    AddTextEntry("tr_pdexp_flag_12", "[TR] Switzerland Flag")
    AddTextEntry("tr_pdexp_flag_13", "[TR] Jamaica Flag")
    AddTextEntry("tr_pdexp_flag_14", "[TR] Colombia Flag")
    AddTextEntry("tr_pdexp_flag_15", "[TR] Norway Flag")
    AddTextEntry("tr_pdexp_flag_16", "[TR] Sweden Flag")
    AddTextEntry("tr_pdexp_flag_17", "[TR] Belgium Flag")
    AddTextEntry("tr_pdexp_flag_18", "[TR] Mexico Flag")
    AddTextEntry("tr_pdexp_flag_19", "[TR] S. Africa Flag")
    AddTextEntry("tr_pdexp_flag_20", "[TR] Russia Flag")
    AddTextEntry("tr_pdexp_flag_21", "[TR] Argentina Flag")
    AddTextEntry("tr_pdexp_flag_22", "[TR] Turkey Flag")
    AddTextEntry("tr_pdexp_flag_23", "[TR] Ireland Flag")
    AddTextEntry("tr_pdexp_flag_24", "[TR] Wales Flag")
    AddTextEntry("tr_pdexp_flag_25", "[TR] England Flag")
    AddTextEntry("tr_pdexp_rambar", "[TR] RamBar")
    AddTextEntry("tr_pdexp_gunrack_2a", "[TR] Gun Rack K9 Version")
    AddTextEntry("tr_pdexp_divider_1a", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pdexp_divider_2a", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pdexp_divider_1b", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pdexp_divider_2b", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pdexp_trunk_a", "[TR] Trunk A")
    AddTextEntry("tr_pdexp_trunk_b", "[TR] Trunk B")
    AddTextEntry("tr_pdexp_trunk_c", "[TR] Trunk C")
    AddTextEntry("tr_pdexp_callsign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdexp_callsign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdexp_callsign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdexp_callsign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdexp_callsign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdexp_callsign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdexp_callsign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdexp_callsign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdexp_callsign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdexp_callsign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdexp_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdexp_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdexp_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdexp_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdexp_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdexp_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdexp_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdexp_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdexp_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdexp_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdexp_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdexp_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdexp_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdexp_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdexp_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdexp_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdexp_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdexp_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdexp_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdexp_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdexp_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pdexp_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pdexp_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pdexp_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pdexp_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pdexp_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pdexp_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pdexp_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pdexp_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pdexp_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pdexp_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pdexp_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pdexp_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pdexp_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pdexp_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pdexp_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pdexp_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pdexp_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pdexp_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pdexp_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("sticker_001", "[TR] Sticker 1")
    AddTextEntry("sticker_002", "[TR] Sticker 2")
    AddTextEntry("sticker_003", "[TR] Sticker 3")
    AddTextEntry("sticker_004", "[TR] Sticker 4")
    AddTextEntry("sticker_005", "[TR] Sticker 5")
    AddTextEntry("sticker_006", "[TR] Sticker 6")
    AddTextEntry("sticker_007", "[TR] Sticker 7")
    AddTextEntry("sticker_008", "[TR] Sticker 8")
    AddTextEntry("sticker_009", "[TR] Sticker 9")
    AddTextEntry("sticker_010", "[TR] Sticker 10")
    AddTextEntry("sticker_011", "[TR] Sticker 11")
    AddTextEntry("sticker_012", "[TR] Sticker 12")
    AddTextEntry("sticker_013", "[TR] Sticker 13")
    AddTextEntry("sticker_014", "[TR] Sticker 14")
    AddTextEntry("sticker_015", "[TR] Sticker 15")
    AddTextEntry("sticker_016", "[TR] Sticker 16")
    AddTextEntry("sticker_017", "[TR] Sticker 17")
    AddTextEntry("sticker_018", "[TR] Sticker 18")
    AddTextEntry("sticker_019", "[TR] Sticker 19")
    AddTextEntry("sticker_020", "[TR] Sticker 20")
    AddTextEntry("sticker_021", "[TR] Sticker 21")
    AddTextEntry("sticker_022", "[TR] Sticker 22")
    AddTextEntry("sticker_023", "[TR] Sticker 23")
    AddTextEntry("sticker_024", "[TR] Sticker 24")
    AddTextEntry("sticker_025", "[TR] Sticker 25")
    AddTextEntry("sticker_026", "[TR] Sticker 26")
    AddTextEntry("sticker_027", "[TR] Sticker 27")
    AddTextEntry("sticker_028", "[TR] Sticker 28")
    AddTextEntry("sticker_029", "[TR] Sticker 29")
    AddTextEntry("sticker_030", "[TR] Sticker 30")
    AddTextEntry("sticker_031", "[TR] Sticker 31")
    AddTextEntry("sticker_032", "[TR] Sticker 32")
    AddTextEntry("sticker_033", "[TR] Sticker 33")
    AddTextEntry("sticker_034", "[TR] Sticker 34")
    AddTextEntry("sticker_035", "[TR] Sticker 35")
    AddTextEntry("sticker_036", "[TR] Sticker 36")
    AddTextEntry("sticker_037", "[TR] Sticker 37")
    AddTextEntry("sticker_038", "[TR] Sticker 38")
    AddTextEntry("sticker_039", "[TR] Sticker 39")
    AddTextEntry("sticker_040", "[TR] Sticker 40")
    AddTextEntry("sticker_041", "[TR] Sticker 41")
    AddTextEntry("sticker_042", "[TR] Sticker 42")
    AddTextEntry("sticker_043", "[TR] Sticker 43")
    AddTextEntry("sticker_044", "[TR] Sticker 44")
    AddTextEntry("sticker_045", "[TR] Sticker 45")
    AddTextEntry("sticker_046", "[TR] Sticker 46")
    AddTextEntry("sticker_047", "[TR] Sticker 47")
    AddTextEntry("sticker_048", "[TR] Sticker 48")
    AddTextEntry("sticker_049", "[TR] Sticker 49")
    AddTextEntry("sticker_050", "[TR] Sticker 50")
    AddTextEntry("tr_pdexp_ant_1a", "[TR] Local Range")
    AddTextEntry("tr_pdexp_ant_2a", "[TR] County Range")
    AddTextEntry("tr_pdexp_ant_1b", "[TR] State Range")
    AddTextEntry("tr_pdexp_livery_1", "[TR] LSPD Livery")
    AddTextEntry("tr_pdexp_livery_2", "[TR] LSPD K9 Livery")
    AddTextEntry("tr_pdexp_livery_3", "[TR] Sheriff Livery")
    AddTextEntry("tr_pdexp_livery_4", "[TR] Sheriff K9 Livery")
    AddTextEntry("tr_pdexp_livery_5", "[TR] State Livery")
    AddTextEntry("tr_pdexp_livery_6", "[TR] State K9 Livery")
    AddTextEntry("tr_pdexp_livery_7", "[TR] Ranger Livery")
    AddTextEntry("tr_pdexp_livery_8", "[TR] Ranger K9 Livery")
    AddTextEntry("tr_pdexp_livery_9", "[TR] Blank")
    AddTextEntry("tr_pdexp_livery_10", "[TR] Blank")
    AddTextEntry("tr_pdexp_rank_1a", "[TR] Supv")
    AddTextEntry("tr_pdexp_rank_1b", "[TR] Command.")

    -- 2018 Generic Taurus
    
    AddTextEntry("tr_pdtaurus_callsign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdtaurus_callsign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdtaurus_callsign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdtaurus_callsign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdtaurus_callsign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdtaurus_callsign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdtaurus_callsign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdtaurus_callsign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdtaurus_callsign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdtaurus_callsign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdtaurus_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdtaurus_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdtaurus_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdtaurus_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdtaurus_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdtaurus_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdtaurus_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdtaurus_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdtaurus_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdtaurus_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdtaurus_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdtaurus_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdtaurus_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdtaurus_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdtaurus_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdtaurus_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdtaurus_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdtaurus_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdtaurus_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdtaurus_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdtaurus_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pdtaurus_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pdtaurus_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pdtaurus_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pdtaurus_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pdtaurus_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pdtaurus_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pdtaurus_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pdtaurus_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pdtaurus_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pdtaurus_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pdtaurus_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pdtaurus_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pdtaurus_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pdtaurus_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pdtaurus_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pdtaurus_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pdtaurus_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pdtaurus_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pdtaurus_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_pdtaurus_rambar_1a", "[TR] RamBar")
    AddTextEntry("tr_pdtaurus_rambar_1b", "[TR] SASP Rambar")
    AddTextEntry("tr_pdtaurus_rambar_2b", "[TR] SAPR Rambar")
    AddTextEntry("tr_pdtaurus_ant_1a", "[TR] LSPD Aerial")
    AddTextEntry("tr_pdtaurus_ant_2a", "[TR] BSCO Aerial")
    AddTextEntry("tr_pdtaurus_ant_3a", "[TR] SASP Aerial")
    AddTextEntry("tr_pdtaurus_doorstuff_inside", "[TR] Window Bars")
    AddTextEntry("tr_pdtaurus_divider_1a", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pdtaurus_divider_2a", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pdtaurus_divider_1b", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pdtaurus_divider_2b", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pdtaurus_trunk_1a", "[TR] Trunk Gear 1")
    AddTextEntry("tr_pdtaurus_trunk_1b", "[TR] Trunk Gear 2")
    AddTextEntry("tr_pdtaurus_trunk_1c", "[TR] Trunk Gear 3")
    AddTextEntry("tr_pdtaurus_livery1", "[TR] LSPD Livery")
    AddTextEntry("tr_pdtaurus_livery2", "[TR] LSPD K9 Livery")
    AddTextEntry("tr_pdtaurus_livery3", "[TR] Sheriff Livery")
    AddTextEntry("tr_pdtaurus_livery4", "[TR] Sheriff K9 Livery")
    AddTextEntry("tr_pdtaurus_livery5", "[TR] State Livery")
    AddTextEntry("tr_pdtaurus_livery6", "[TR] State K9 Livery")
    AddTextEntry("tr_pdtaurus_livery7", "[TR] Ranger Livery")
    AddTextEntry("tr_pdtaurus_livery8", "[TR] Ranger K9 Livery")
    AddTextEntry("tr_pdtaurus_super", "[TR] Supv.")
    AddTextEntry("tr_pdtaurus_com", "[TR] Com.")
    AddTextEntry("tr_pdtaurus_sticker_001", "[TR] Sticker 1")
    AddTextEntry("tr_pdtaurus_sticker_002", "[TR] Sticker 2")
    AddTextEntry("tr_pdtaurus_sticker_003", "[TR] Sticker 3")
    AddTextEntry("tr_pdtaurus_sticker_004", "[TR] Sticker 4")
    AddTextEntry("tr_pdtaurus_sticker_005", "[TR] Sticker 5")
    AddTextEntry("tr_pdtaurus_sticker_006", "[TR] Sticker 6")
    AddTextEntry("tr_pdtaurus_sticker_007", "[TR] Sticker 7")
    AddTextEntry("tr_pdtaurus_sticker_008", "[TR] Sticker 8")
    AddTextEntry("tr_pdtaurus_sticker_009", "[TR] Sticker 9")
    AddTextEntry("tr_pdtaurus_sticker_010", "[TR] Sticker 10")

    --EMS EXP (Medical)
    AddTextEntry("tr_emsexp_callsign_a0", "[TR] Callsign A")
    AddTextEntry("tr_emsexp_callsign_a1", "[TR] Callsign B")
    AddTextEntry("tr_emsexp_callsign_a2", "[TR] Callsign C")
    AddTextEntry("tr_emsexp_callsign_a3", "[TR] Callsign D")
    AddTextEntry("tr_emsexp_callsign_a4", "[TR] Callsign E")
    AddTextEntry("tr_emsexp_callsign_a5", "[TR] Callsign F")
    AddTextEntry("tr_emsexp_callsign_a6", "[TR] Callsign G")
    AddTextEntry("tr_emsexp_callsign_a7", "[TR] Callsign H")
    AddTextEntry("tr_emsexp_callsign_a8", "[TR] Callsign I")
    AddTextEntry("tr_emsexp_callsign_a9", "[TR] Callsign J")
    AddTextEntry("tr_emsexp_callsign_a10", "[TR] Callsign K")
    AddTextEntry("tr_emsexp_callsign_a11", "[TR] Callsign L")
    AddTextEntry("tr_emsexp_callsign_a12", "[TR] Callsign M")
    AddTextEntry("tr_emsexp_callsign_a13", "[TR] Callsign N")
    AddTextEntry("tr_emsexp_callsign_a14", "[TR] Callsign O")
    AddTextEntry("tr_emsexp_callsign_a15", "[TR] Callsign P")
    AddTextEntry("tr_emsexp_callsign_a16", "[TR] Callsign Q")
    AddTextEntry("tr_emsexp_callsign_a17", "[TR] Callsign R")
    AddTextEntry("tr_emsexp_callsign_a18", "[TR] Callsign S")
    AddTextEntry("tr_emsexp_callsign_a19", "[TR] Callsign T")
    AddTextEntry("tr_emsexp_callsign_a20", "[TR] Callsign U")
    AddTextEntry("tr_emsexp_callsign_a21", "[TR] Callsign V")
    AddTextEntry("tr_emsexp_callsign_a22", "[TR] Callsign W")
    AddTextEntry("tr_emsexp_callsign_a23", "[TR] Callsign X")
    AddTextEntry("tr_emsexp_callsign_a24", "[TR] Callsign Y")
    AddTextEntry("tr_emsexp_callsign_a25", "[TR] Callsign Z")
    AddTextEntry("tr_emsexp_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_emsexp_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_emsexp_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_emsexp_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_emsexp_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_emsexp_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_emsexp_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_emsexp_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_emsexp_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_emsexp_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_emsexp_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_emsexp_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_emsexp_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_emsexp_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_emsexp_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_emsexp_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_emsexp_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_emsexp_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_emsexp_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_emsexp_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_emsexp_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_emsexp_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_emsexp_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_emsexp_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_emsexp_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_emsexp_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_emsexp_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_emsexp_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_emsexp_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_emsexp_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_emsexp_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_emsexp_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_emsexp_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_emsexp_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_emsexp_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_emsexp_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_emsexp_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_emsexp_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_emsexp_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_emsexp_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_emsexp_fan_set1", "[TR] PGR. Fan")
    AddTextEntry("tr_emsexp_livery1", "[TR] EMS Livery 1")
    AddTextEntry("tr_emsexp_livery2", "[TR] EMS Livery 2")
    AddTextEntry("tr_emsexp_rambar", "[TR] EMS Pushbar")
    AddTextEntry("tr_emsexp_seat", "[TR] Middle Seats")
    AddTextEntry("tr_emsexp_seatback", "[TR] Mid/Back Seats")
    AddTextEntry("tr_emsexp_rank_com", "[TR] Comm. Rank")
    AddTextEntry("tr_emsexp_rank_supv", "[TR] Supv. Rank")
    AddTextEntry("tr_emsexp_trunk_1a", "[TR] Medical Bags")
    AddTextEntry("tr_emsexp_trunk_2a", "[TR] Med. Bags/Axe")
    AddTextEntry("tr_emsexp_trunk_3a", "[TR] Blue Bags H/ Full")
    AddTextEntry("tr_emsexp_trunk_4a", "[TR] Blue Bags Full")
    AddTextEntry("tr_emsexp_trunk_5a", "[TR] Mixed Bags H/ Full")
    AddTextEntry("tr_emsexp_trunk_6a", "[TR] Mixed Bags Full")
    AddTextEntry("tr_emsexp_trunk_4b", "[TR] Blue Bags w/ axe")
    AddTextEntry("tr_emsexp_trunk_6b", "[TR] Mixed Bags w/ axe")
    AddTextEntry("tr_emsexp_w_1a", "[TR] Med. Service")
    AddTextEntry("tr_emsexp_w_2a", "[TR] Paramedic")
    AddTextEntry("tr_emsexp_flag_01", "[TR] USA Flag")
    AddTextEntry("tr_emsexp_flag_02", "[TR] AU Flag")
    AddTextEntry("tr_emsexp_flag_03", "[TR] Brazil Flag")
    AddTextEntry("tr_emsexp_flag_04", "[TR] Spain Flag")
    AddTextEntry("tr_emsexp_flag_05", "[TR] canada Flag")
    AddTextEntry("tr_emsexp_flag_06", "[TR] France Flag")
    AddTextEntry("tr_emsexp_flag_07", "[TR] Germany Flag")
    AddTextEntry("tr_emsexp_flag_08", "[TR] Japan Flag")
    AddTextEntry("tr_emsexp_flag_09", "[TR] Scotland Flag")
    AddTextEntry("tr_emsexp_flag_10", "[TR] UK Flag")
    AddTextEntry("tr_emsexp_flag_11", "[TR] Italy Flag")
    AddTextEntry("tr_emsexp_flag_12", "[TR] Switzerland Flag")
    AddTextEntry("tr_emsexp_flag_13", "[TR] Jamaica Flag")
    AddTextEntry("tr_emsexp_flag_14", "[TR] Colombia Flag")
    AddTextEntry("tr_emsexp_flag_15", "[TR] Norway Flag")
    AddTextEntry("tr_emsexp_flag_16", "[TR] Sweden Flag")
    AddTextEntry("tr_emsexp_flag_17", "[TR] Belgium Flag")
    AddTextEntry("tr_emsexp_flag_18", "[TR] Mexico Flag")
    AddTextEntry("tr_emsexp_flag_19", "[TR] S. Africa Flag")
    AddTextEntry("tr_emsexp_flag_20", "[TR] Russia Flag")
    AddTextEntry("tr_emsexp_flag_21", "[TR] Argentina Flag")
    AddTextEntry("tr_emsexp_flag_22", "[TR] Turkey Flag")
    AddTextEntry("tr_emsexp_flag_23", "[TR] Ireland Flag")
    AddTextEntry("tr_emsexp_flag_24", "[TR] Wales Flag")
    AddTextEntry("tr_emsexp_flag_25", "[TR] England Flag")
    AddTextEntry("tr_emsexp_ant_1a", "[TR] Local Range")
    AddTextEntry("tr_emsexp_ant_2a", "[TR] County Range")
    AddTextEntry("tr_emsexp_ant_1b", "[TR] State Range")

    -- EMS AMBO
    AddTextEntry("tr_emsambo_callsign_a0", "[TR] Callsign A")
    AddTextEntry("tr_emsambo_callsign_a1", "[TR] Callsign B")
    AddTextEntry("tr_emsambo_callsign_a2", "[TR] Callsign C")
    AddTextEntry("tr_emsambo_callsign_a3", "[TR] Callsign D")
    AddTextEntry("tr_emsambo_callsign_a4", "[TR] Callsign E")
    AddTextEntry("tr_emsambo_callsign_a5", "[TR] Callsign F")
    AddTextEntry("tr_emsambo_callsign_a6", "[TR] Callsign G")
    AddTextEntry("tr_emsambo_callsign_a7", "[TR] Callsign H")
    AddTextEntry("tr_emsambo_callsign_a8", "[TR] Callsign I")
    AddTextEntry("tr_emsambo_callsign_a9", "[TR] Callsign J")
    AddTextEntry("tr_emsambo_callsign_a10", "[TR] Callsign K")
    AddTextEntry("tr_emsambo_callsign_a11", "[TR] Callsign L")
    AddTextEntry("tr_emsambo_callsign_a12", "[TR] Callsign M")
    AddTextEntry("tr_emsambo_callsign_a13", "[TR] Callsign N")
    AddTextEntry("tr_emsambo_callsign_a14", "[TR] Callsign O")
    AddTextEntry("tr_emsambo_callsign_a15", "[TR] Callsign P")
    AddTextEntry("tr_emsambo_callsign_a16", "[TR] Callsign Q")
    AddTextEntry("tr_emsambo_callsign_a17", "[TR] Callsign R")
    AddTextEntry("tr_emsambo_callsign_a18", "[TR] Callsign S")
    AddTextEntry("tr_emsambo_callsign_a19", "[TR] Callsign T")
    AddTextEntry("tr_emsambo_callsign_a20", "[TR] Callsign U")
    AddTextEntry("tr_emsambo_callsign_a21", "[TR] Callsign V")
    AddTextEntry("tr_emsambo_callsign_a22", "[TR] Callsign W")
    AddTextEntry("tr_emsambo_callsign_a23", "[TR] Callsign X")
    AddTextEntry("tr_emsambo_callsign_a24", "[TR] Callsign Y")
    AddTextEntry("tr_emsambo_callsign_a25", "[TR] Callsign Z")
    AddTextEntry("tr_emsambo_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_emsambo_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_emsambo_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_emsambo_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_emsambo_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_emsambo_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_emsambo_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_emsambo_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_emsambo_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_emsambo_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_emsambo_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_emsambo_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_emsambo_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_emsambo_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_emsambo_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_emsambo_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_emsambo_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_emsambo_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_emsambo_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_emsambo_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_emsambo_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_emsambo_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_emsambo_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_emsambo_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_emsambo_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_emsambo_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_emsambo_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_emsambo_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_emsambo_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_emsambo_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_emsambo_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_emsambo_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_emsambo_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_emsambo_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_emsambo_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_emsambo_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_emsambo_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_emsambo_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_emsambo_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_emsambo_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_emsambo_livery1", "[TR] EMS Livery 1")
    AddTextEntry("tr_emsambo_livery2", "[TR] EMS Livery 2")
    AddTextEntry("tr_emsambo_ant_1a", "[TR] state Range")
    AddTextEntry("tr_emsambo_rwnull_1a", "[TR] Black/Red Window Decal")
    AddTextEntry("tr_emsambo_rwnull_1b", "[TR] Blue Window Decal")
    AddTextEntry("tr_emsambo_rwnull_1c", "[TR] Red Window Decal")
    AddTextEntry("tr_emsambo_box_1a", "[TR] Ambulance Decal")
    AddTextEntry("tr_emsambo_windowdecal_1a", "[TR] Paramedic")
    AddTextEntry("tr_emsambo_windowdecal_2a", "[TR] Med. Service")
    AddTextEntry("tr_emsambo_nwnull_1a", "[TR] First / Last Name")
    AddTextEntry("tr_emsambo_rank_1a", "[TR] Supervisor")
    AddTextEntry("tr_emsambo_rank_1b", "[TR] Command")

    -- Durango
    AddTextEntry("tr_pddurango_flag_1", "[TR] USA Flag")
    AddTextEntry("tr_pddurango_flag_2", "[TR] AU Flag")
    AddTextEntry("tr_pddurango_flag_3", "[TR] Brazil Flag")
    AddTextEntry("tr_pddurango_flag_4", "[TR] Spain Flag")
    AddTextEntry("tr_pddurango_flag_5", "[TR] canada Flag")
    AddTextEntry("tr_pddurango_flag_6", "[TR] France Flag")
    AddTextEntry("tr_pddurango_flag_7", "[TR] Germany Flag")
    AddTextEntry("tr_pddurango_flag_8", "[TR] Japan Flag")
    AddTextEntry("tr_pddurango_flag_9", "[TR] Scotland Flag")
    AddTextEntry("tr_pddurango_flag_10", "[TR] UK Flag")
    AddTextEntry("tr_pddurango_flag_11", "[TR] Italy Flag")
    AddTextEntry("tr_pddurango_flag_12", "[TR] Switzerland Flag")
    AddTextEntry("tr_pddurango_flag_13", "[TR] Jamaica Flag")
    AddTextEntry("tr_pddurango_flag_14", "[TR] Colombia Flag")
    AddTextEntry("tr_pddurango_flag_15", "[TR] Norway Flag")
    AddTextEntry("tr_pddurango_flag_16", "[TR] Sweden Flag")
    AddTextEntry("tr_pddurango_flag_17", "[TR] Belgium Flag")
    AddTextEntry("tr_pddurango_flag_18", "[TR] Mexico Flag")
    AddTextEntry("tr_pddurango_flag_19", "[TR] S. Africa Flag")
    AddTextEntry("tr_pddurango_flag_20", "[TR] Russia Flag")
    AddTextEntry("tr_pddurango_flag_21", "[TR] Argentina Flag")
    AddTextEntry("tr_pddurango_flag_22", "[TR] Turkey Flag")
    AddTextEntry("tr_pddurango_flag_23", "[TR] Ireland Flag")
    AddTextEntry("tr_pddurango_flag_24", "[TR] Wales Flag")
    AddTextEntry("tr_pddurango_flag_25", "[TR] England Flag")
    AddTextEntry("tr_pddurango_ram_1a", "[TR] RamBar")
    AddTextEntry("tr_pddurango_ram_2a", "[TR] RamBar / Wrap Around")
    AddTextEntry("tr_pddurango_divider_1a", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pddurango_divider_2a", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pddurango_divider_1b", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pddurango_divider_2b", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pddurango_callsign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pddurango_callsign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pddurango_callsign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pddurango_callsign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pddurango_callsign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pddurango_callsign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pddurango_callsign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pddurango_callsign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pddurango_callsign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pddurango_callsign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pddurango_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pddurango_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pddurango_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pddurango_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pddurango_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pddurango_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pddurango_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pddurango_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pddurango_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pddurango_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pddurango_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pddurango_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pddurango_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pddurango_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pddurango_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pddurango_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pddurango_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pddurango_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pddurango_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pddurango_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pddurango_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pddurango_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pddurango_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pddurango_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pddurango_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pddurango_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pddurango_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pddurango_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pddurango_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pddurango_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pddurango_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pddurango_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pddurango_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pddurango_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pddurango_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pddurango_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pddurango_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pddurango_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pddurango_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pddurango_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_pddurango_badge_rear", "[TR] SRU Badges")
    AddTextEntry("tr_pddurango_ant_1a", "[TR] State Range")
    AddTextEntry("tr_pddurango_livery_1", "[TR] LSPD Livery")
    AddTextEntry("tr_pddurango_livery_2", "[TR] Sheriff Livery")
    AddTextEntry("tr_pddurango_livery_3", "[TR] State Livery")
    AddTextEntry("tr_pddurango_livery_4", "[TR] Park Ranger Livery")
    AddTextEntry("tr_pddurango_livery_5", "[TR] SRU Livery")
    AddTextEntry("rank1", "[TR] Supv")
    AddTextEntry("rank2", "[TR] Command.")
    AddTextEntry("tr_pddurango_radar", "[TR] Radar.")
    AddTextEntry("tr_pddurango_srt", "[TR] SRU Kit.")

    -- TR CB PDBike
    AddTextEntry("tr_pdbike_storage", "[TR] Storage")
    AddTextEntry("tr_pdbike_livery1", "[TR] LSPD Livery")
    AddTextEntry("tr_pdbike_livery2", "[TR] Sheriff Livery")
    AddTextEntry("tr_pdbike_livery3", "[TR] Ranger Livery")
    AddTextEntry("tr_pdbike_livery4", "[TR] Trooper Livery")

    -- TR Char2
    AddTextEntry("tr_pdchar2spoil_1", "[TR] Prim Spoiler")
	AddTextEntry("tr_pdchar2spoil_2", "[TR] Second Spoiler")
	AddTextEntry("tr_pdchar2spoil_3", "[TR] Carbon Spoiler")
	AddTextEntry("tr_pdchar2roof_1", "[TR] Secondary Roof")
	AddTextEntry("tr_pdchar2roof_2", "[TR] Carbon Roof")
	AddTextEntry("tr_pdchar2_null_1", "[TR] Secondary Mirror")
	AddTextEntry("tr_pdchar2_null_2", "[TR] Carbon Mirror")
	AddTextEntry("tr_pdchar2_hood_1", "[TR] Secondary Hood")
	AddTextEntry("tr_pdchar2_hood_2", "[TR] Carbon Hood")
	AddTextEntry("tr_pdchar2_null_4", "[TR] Prim Door Color")
	AddTextEntry("tr_pdchar2_gunrack", "[TR] Gun Rack Only")
	AddTextEntry("tr_pdchar2_divider_1a", "[TR] Gun Rack / Divider")
	AddTextEntry("tr_pdchar2_divider_2a", "[TR] Gun Rack / Divider Cam")
	AddTextEntry("tr_pdchar2_divider_1b", "[TR]Gun Rack / Divider Open")
	AddTextEntry("tr_pdchar2_divider_2b", "[TR] Gun Rack / Divider Cam")
	AddTextEntry("tr_pdchar2_rambar", "[TR] Rambar")
    AddTextEntry("tr_pdchar2_csign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar2_csign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar2_csign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar2_csign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar2_csign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar2_csign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar2_csign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar2_csign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar2_csign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar2_csign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar2_csign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar2_csign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar2_csign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar2_csign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar2_csign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar2_csign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar2_csign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar2_csign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar2_csign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar2_csign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar2_csign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar2_csign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar2_csign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar2_csign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar2_csign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar2_csign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar2_csign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar2_csign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar2_csign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar2_csign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar2_csign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar2_csign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar2_csign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar2_csign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar2_csign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar2_csign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar2_csign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar2_csign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar2_csign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar2_csign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar2_csign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar2_csign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar2_csign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar2_csign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar2_csign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar2_csign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar2_csign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar2_csign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar2_csign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar2_csign_e9", "[TR] CallSign 9")
	AddTextEntry("tr_pdchar2_livery1", "[TR] LSPD livery")
	AddTextEntry("tr_pdchar2_livery2", "[TR] BSCO livery")
	AddTextEntry("tr_pdchar2_livery3", "[TR] SAPR livery")
	AddTextEntry("tr_pdchar2_livery4", "[TR] State livery")
	AddTextEntry("tr_pdchar2_doorrank_1", "[TR] Supervisor Rank")
	AddTextEntry("tr_pdchar2_doorrank_2", "[TR] Command Rank")
	AddTextEntry("tr_pdchar2_doorrank_2", "[TR] Command Rank")
	AddTextEntry("tr_pdchar2_ant_a1", "[TR] State Range")
	AddTextEntry("tr_pdchar2_ant_b1", "[TR] BSCO/LSPD Range")

    -- Silv
    AddTextEntry("tr_pdsilv_rack", "[TR] ToolRack")
    AddTextEntry("tr_pdsilv_rack2", "[TR] ToolRack 2")
    AddTextEntry("tr_pdsilv_rambar", "[TR] RamBar")
    AddTextEntry("tr_pdsilv_divider_1a", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pdsilv_divider_2a", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pdsilv_divider_1b", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pdsilv_divider_2b", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pdsilv_callsign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdsilv_callsign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdsilv_callsign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdsilv_callsign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdsilv_callsign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdsilv_callsign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdsilv_callsign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdsilv_callsign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdsilv_callsign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdsilv_callsign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdsilv_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdsilv_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdsilv_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdsilv_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdsilv_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdsilv_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdsilv_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdsilv_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdsilv_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdsilv_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdsilv_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdsilv_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdsilv_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdsilv_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdsilv_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdsilv_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdsilv_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdsilv_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdsilv_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdsilv_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdsilv_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pdsilv_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pdsilv_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pdsilv_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pdsilv_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pdsilv_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pdsilv_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pdsilv_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pdsilv_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pdsilv_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pdsilv_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pdsilv_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pdsilv_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pdsilv_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pdsilv_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pdsilv_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pdsilv_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pdsilv_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pdsilv_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pdsilv_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_pdsilv_ant_1a", "[TR] State Range")
    AddTextEntry("tr_pdsilv_livery_1", "[TR] LSPD Livery")
    AddTextEntry("tr_pdsilv_livery_2", "[TR] Sheriff Livery")
    AddTextEntry("tr_pdsilv_livery_4", "[TR] State Livery")
    AddTextEntry("tr_pdsilv_livery_3", "[TR] Park Ranger Livery")
    AddTextEntry("tr_pdsilv_rank1", "[TR] Supv")
    AddTextEntry("tr_pdsilv_rank2", "[TR] Command.")
end)