function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry("tr_pdsilv_rack", "[TR] ToolRack")
    AddTextEntry("tr_pdsilv_rack2", "[TR] ToolRack 2")
    AddTextEntry("tr_pdsilv_rambar", "[TR] RamBar")
    AddTextEntry("tr_pdsilv_divider_1a", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pdsilv_divider_2a", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pdsilv_divider_1b", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pdsilv_divider_2b", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pdsilv_callsign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdsilv_callsign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdsilv_callsign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdsilv_callsign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdsilv_callsign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdsilv_callsign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdsilv_callsign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdsilv_callsign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdsilv_callsign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdsilv_callsign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdsilv_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdsilv_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdsilv_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdsilv_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdsilv_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdsilv_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdsilv_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdsilv_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdsilv_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdsilv_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdsilv_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdsilv_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdsilv_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdsilv_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdsilv_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdsilv_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdsilv_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdsilv_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdsilv_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdsilv_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdsilv_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pdsilv_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pdsilv_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pdsilv_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pdsilv_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pdsilv_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pdsilv_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pdsilv_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pdsilv_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pdsilv_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pdsilv_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pdsilv_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pdsilv_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pdsilv_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pdsilv_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pdsilv_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pdsilv_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pdsilv_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pdsilv_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pdsilv_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_pdsilv_ant_1a", "[TR] State Range")
    AddTextEntry("tr_pdsilv_livery_1", "[TR] LSPD Livery")
    AddTextEntry("tr_pdsilv_livery_2", "[TR] Sheriff Livery")
    AddTextEntry("tr_pdsilv_livery_4", "[TR] State Livery")
    AddTextEntry("tr_pdsilv_livery_3", "[TR] Park Ranger Livery")
    AddTextEntry("tr_pdsilv_rank1", "[TR] Supv")
    AddTextEntry("tr_pdsilv_rank2", "[TR] Command.")
end)
