function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry("tr_pdchar_perform", "[TR] Performance Package")
    AddTextEntry("tr_pdchar_spoiler_1", "[TR] SRT Spoiler (SGT)")
    AddTextEntry("tr_pdchar_spoiler_2", "[TR] Hellcat")
    AddTextEntry("tr_pdchar_spoiler_3", "[TR] Hellcat Spoiler (SRU Leaders)")
    AddTextEntry("tr_pdchar_rearbadge", "[TR] SRU Badges (Non-WideBody)")
    AddTextEntry("tr_pdchar_trunk_a1", "[TR] Gun Case")
    AddTextEntry("tr_pdchar_trunk_b1", "[TR] Gun Case w/Magz")
    AddTextEntry("tr_pdchar_trunk_b2", "[TR] Gun Case w/ Fire Ext.")
    AddTextEntry("tr_pdchar_trunk_c1", "[TR] Full Trunk")
    AddTextEntry("tr_pdchar_trunk_c2", "[TR] Full Trunk 2")
    AddTextEntry("tr_pdchar_convar", "[TR] WideBody for Hellcat Conversion (SRU Leaders)")
    AddTextEntry("tr_pdchar_divider_1a", "[TR] Divider w/gun")
    AddTextEntry("tr_pdchar_divider_2a", "[TR] Divider w/gun & Cam")
    AddTextEntry("tr_pdchar_divider_1b", "[TR] Divider Open w/gun")
    AddTextEntry("tr_pdchar_divider_2b", "[TR] Divider Open w/gun & Cam")
    AddTextEntry("tr_pdchar_rank1", "[TR] Command")
    AddTextEntry("tr_pdchar_rank2", "[TR] Supv.")
    AddTextEntry("tr_pdchar_ram_1a", "[TR] RamBar")
    AddTextEntry("tr_pdchar_callsign_a0", "[TR] RamBar")
    AddTextEntry("tr_pdchar_callsign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar_callsign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar_callsign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar_callsign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar_callsign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar_callsign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar_callsign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar_callsign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar_callsign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar_callsign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pdchar_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pdchar_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pdchar_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pdchar_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pdchar_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pdchar_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pdchar_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pdchar_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pdchar_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_pdchar_ant_1a_v1", "[TR] Local PD")
    AddTextEntry("tr_pdchar_ant_1a_v2", "[TR] BSCO")
    AddTextEntry("tr_pdchar_ant_1b", "[TR] State")
    AddTextEntry("tr_pdchar_livery1", "[TR] LSPD Livery")
    AddTextEntry("tr_pdchar_livery2", "[TR] BSCO Livery")
    AddTextEntry("tr_pdchar_livery3", "[TR] State Livery")
    AddTextEntry("tr_pdchar_livery4", "[TR] Ranger Livery")
    AddTextEntry("tr_pdchar_livery5", "[TR] SRU Livery")
    AddTextEntry("sru_wheel_widebody", "[TR] SRU Widebody Wheel")
    AddTextEntry("sru_wheel_non_widebody", "[TR] Sru Wheel Non-Widebody")
end)
