function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry("tr_pdtaurus_callsign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdtaurus_callsign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdtaurus_callsign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdtaurus_callsign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdtaurus_callsign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdtaurus_callsign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdtaurus_callsign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdtaurus_callsign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdtaurus_callsign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdtaurus_callsign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdtaurus_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdtaurus_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdtaurus_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdtaurus_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdtaurus_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdtaurus_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdtaurus_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdtaurus_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdtaurus_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdtaurus_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdtaurus_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdtaurus_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdtaurus_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdtaurus_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdtaurus_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdtaurus_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdtaurus_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdtaurus_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdtaurus_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdtaurus_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdtaurus_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pdtaurus_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pdtaurus_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pdtaurus_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pdtaurus_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pdtaurus_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pdtaurus_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pdtaurus_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pdtaurus_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pdtaurus_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pdtaurus_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pdtaurus_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pdtaurus_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pdtaurus_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pdtaurus_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pdtaurus_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pdtaurus_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pdtaurus_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pdtaurus_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pdtaurus_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_pdtaurus_rambar_1a", "[TR] RamBar")
    AddTextEntry("tr_pdtaurus_rambar_1b", "[TR] SASP Rambar")
    AddTextEntry("tr_pdtaurus_rambar_2b", "[TR] SAPR Rambar")
    AddTextEntry("tr_pdtaurus_ant_1a", "[TR] LSPD Aerial")
    AddTextEntry("tr_pdtaurus_ant_2a", "[TR] BSCO Aerial")
    AddTextEntry("tr_pdtaurus_ant_3a", "[TR] SASP Aerial")
    AddTextEntry("tr_pdtaurus_doorstuff_inside", "[TR] Window Bars")
    AddTextEntry("tr_pdtaurus_divider_1a", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pdtaurus_divider_2a", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pdtaurus_divider_1b", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pdtaurus_divider_2b", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pdtaurus_trunk_1a", "[TR] Trunk Gear 1")
    AddTextEntry("tr_pdtaurus_trunk_1b", "[TR] Trunk Gear 2")
    AddTextEntry("tr_pdtaurus_trunk_1c", "[TR] Trunk Gear 3")
    AddTextEntry("tr_pdtaurus_livery1", "[TR] LSPD Livery")
    AddTextEntry("tr_pdtaurus_livery2", "[TR] LSPD K9 Livery")
    AddTextEntry("tr_pdtaurus_livery3", "[TR] Sheriff Livery")
    AddTextEntry("tr_pdtaurus_livery4", "[TR] Sheriff K9 Livery")
    AddTextEntry("tr_pdtaurus_livery5", "[TR] State Livery")
    AddTextEntry("tr_pdtaurus_livery6", "[TR] State K9 Livery")
    AddTextEntry("tr_pdtaurus_livery7", "[TR] Ranger Livery")
    AddTextEntry("tr_pdtaurus_livery8", "[TR] Ranger K9 Livery")
    AddTextEntry("tr_pdtaurus_super", "[TR] Supv.")
    AddTextEntry("tr_pdtaurus_com", "[TR] Com.")
    AddTextEntry("tr_pdtaurus_sticker_001", "[TR] Sticker 1")
    AddTextEntry("tr_pdtaurus_sticker_002", "[TR] Sticker 2")
    AddTextEntry("tr_pdtaurus_sticker_003", "[TR] Sticker 3")
    AddTextEntry("tr_pdtaurus_sticker_004", "[TR] Sticker 4")
    AddTextEntry("tr_pdtaurus_sticker_005", "[TR] Sticker 5")
    AddTextEntry("tr_pdtaurus_sticker_006", "[TR] Sticker 6")
    AddTextEntry("tr_pdtaurus_sticker_007", "[TR] Sticker 7")
    AddTextEntry("tr_pdtaurus_sticker_008", "[TR] Sticker 8")
    AddTextEntry("tr_pdtaurus_sticker_009", "[TR] Sticker 9")
    AddTextEntry("tr_pdtaurus_sticker_010", "[TR] Sticker 10")
end)
