function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry("tr_pddm_csign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pddm_csign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pddm_csign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pddm_csign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pddm_csign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pddm_csign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pddm_csign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pddm_csign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pddm_csign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pddm_csign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pddm_csign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pddm_csign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pddm_csign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pddm_csign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pddm_csign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pddm_csign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pddm_csign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pddm_csign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pddm_csign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pddm_csign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pddm_csign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pddm_csign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pddm_csign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pddm_csign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pddm_csign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pddm_csign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pddm_csign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pddm_csign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pddm_csign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pddm_csign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pddm_csign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pddm_csign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pddm_csign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pddm_csign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pddm_csign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pddm_csign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pddm_csign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pddm_csign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pddm_csign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pddm_csign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pddm_csign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pddm_csign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pddm_csign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pddm_csign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pddm_csign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pddm_csign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pddm_csign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pddm_csign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pddm_csign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pddm_csign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_pddm_livery1", "[TR] Police Livery")
    AddTextEntry("tr_pddm_livery2", "[TR] Sheriff Livery")
    AddTextEntry("tr_pddm_livery3", "[TR] State Livery")
    AddTextEntry("tr_pddm_livery4", "[TR] Ranger Livery")
    AddTextEntry("tr_pddm_livery5", "[TR] SRU Livery")
    AddTextEntry("tr_pddm_livery6", "[TR] Swat Livery")
    AddTextEntry("tr_pddm_rollcage", "[TR] Roll Cage")
    AddTextEntry("tr_pddm_ram_1a", "[TR] Rambar")
    AddTextEntry("tr_pddm_antenna_1a", "[TR] State Range Antenna")
    AddTextEntry("tr_pddm_antenna_1b", "[TR] Local Range Antenna")
    AddTextEntry("tr_pddm_antenna_1c", "[TR] City Range Antenna")
    AddTextEntry("tr_pddm_roof", "[TR] All Black Roof")
end)