function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	AddTextEntry("tr_pdcv_rollcage", "[TR] Roll Cage")
	AddTextEntry("tr_pdcv_zr1badge", "[TR] Hood Badge")
	AddTextEntry("tr_pdcv_zr1skits", "[TR] Skirt Kit")
	AddTextEntry("tr_pdcv_spoiler_1", "[TR] Duck Spoiler Raised")
	AddTextEntry("tr_pdcv_spoiler_2", "[TR] Duck Spoiler Raised/Bolts")
	AddTextEntry("tr_pdcv_spoiler_3", "[TR] Duck Sport Spoiler")
    AddTextEntry("tr_pdcv_riflemount_1", "[TR] Empty Rack")
    AddTextEntry("tr_pdcv_riflemount_2", "[TR] M4A1")
    AddTextEntry("tr_pdcv_riflemount_3", "[TR] M4A1 / SHOTGUN")
    AddTextEntry("tr_pdcv_riflemount_4", "[TR] SHOTGUN")
    AddTextEntry("tr_pdcv_sticker_1", "[TR] Sticker 1")
    AddTextEntry("tr_pdcv_sticker_2", "[TR] Sticker 2")
    AddTextEntry("tr_pdcv_sticker_3", "[TR] Sticker 3")
    AddTextEntry("tr_pdcv_sticker_4", "[TR] Sticker 4")
    AddTextEntry("tr_pdcv_sticker_5", "[TR] Sticker 5")
    AddTextEntry("tr_pdcv_sticker_6", "[TR] Sticker 6")
    AddTextEntry("tr_pdcv_sticker_7", "[TR] Sticker 7")
    AddTextEntry("tr_pdcv_sticker_8", "[TR] Sticker 8")
    AddTextEntry("tr_pdcv_csign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdcv_csign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdcv_csign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdcv_csign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdcv_csign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdcv_csign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdcv_csign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdcv_csign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdcv_csign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdcv_csign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdcv_csign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdcv_csign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdcv_csign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdcv_csign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdcv_csign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdcv_csign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdcv_csign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdcv_csign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdcv_csign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdcv_csign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdcv_csign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdcv_csign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdcv_csign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdcv_csign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdcv_csign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdcv_csign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdcv_csign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdcv_csign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdcv_csign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdcv_csign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdcv_livery1", "[TR] Police Livery")
    AddTextEntry("tr_pdcv_livery2", "[TR] Sheriff Livery")
    AddTextEntry("tr_pdcv_livery3", "[TR] State Livery")
    AddTextEntry("tr_pdcv_livery4", "[TR] Ranger Livery")
    AddTextEntry("tr_pdcv_livery5", "[TR] SRU Livery")
    AddTextEntry("tr_pdcv_livery6", "[TR] Swat Livery")
    AddTextEntry("tr_pdcv_antenna_1a", "[TR] State Range Antenna")
end)
