function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry("tr_pdexpse_1a", "[TR] Back Seats")
    AddTextEntry("tr_pdexp_k9_1a", "[TR] K9 Back Full")
    AddTextEntry("tr_pdexp_k9_1b", "[TR] K9 Back Half")
    AddTextEntry("tr_pdexp_bars_1a", "[TR] Window Bars")
    AddTextEntry("tr_pdexp_flag_01", "[TR] USA Flag")
    AddTextEntry("tr_pdexp_flag_02", "[TR] AU Flag")
    AddTextEntry("tr_pdexp_flag_03", "[TR] Brazil Flag")
    AddTextEntry("tr_pdexp_flag_04", "[TR] Spain Flag")
    AddTextEntry("tr_pdexp_flag_05", "[TR] canada Flag")
    AddTextEntry("tr_pdexp_flag_06", "[TR] France Flag")
    AddTextEntry("tr_pdexp_flag_07", "[TR] Germany Flag")
    AddTextEntry("tr_pdexp_flag_08", "[TR] Japan Flag")
    AddTextEntry("tr_pdexp_flag_09", "[TR] Scotland Flag")
    AddTextEntry("tr_pdexp_flag_10", "[TR] UK Flag")
    AddTextEntry("tr_pdexp_flag_11", "[TR] Italy Flag")
    AddTextEntry("tr_pdexp_flag_12", "[TR] Switzerland Flag")
    AddTextEntry("tr_pdexp_flag_13", "[TR] Jamaica Flag")
    AddTextEntry("tr_pdexp_flag_14", "[TR] Colombia Flag")
    AddTextEntry("tr_pdexp_flag_15", "[TR] Norway Flag")
    AddTextEntry("tr_pdexp_flag_16", "[TR] Sweden Flag")
    AddTextEntry("tr_pdexp_flag_17", "[TR] Belgium Flag")
    AddTextEntry("tr_pdexp_flag_18", "[TR] Mexico Flag")
    AddTextEntry("tr_pdexp_flag_19", "[TR] S. Africa Flag")
    AddTextEntry("tr_pdexp_flag_20", "[TR] Russia Flag")
    AddTextEntry("tr_pdexp_flag_21", "[TR] Argentina Flag")
    AddTextEntry("tr_pdexp_flag_22", "[TR] Turkey Flag")
    AddTextEntry("tr_pdexp_flag_23", "[TR] Ireland Flag")
    AddTextEntry("tr_pdexp_flag_24", "[TR] Wales Flag")
    AddTextEntry("tr_pdexp_flag_25", "[TR] England Flag")
    AddTextEntry("tr_pdexp_rambar", "[TR] RamBar")
    AddTextEntry("tr_pdexp_gunrack_2a", "[TR] Gun Rack K9 Version")
    AddTextEntry("tr_pdexp_divider_1a", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pdexp_divider_2a", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pdexp_divider_1b", "[TR] Divider w/ Gun")
    AddTextEntry("tr_pdexp_divider_2b", "[TR] Divider w/ Gun & Cam")
    AddTextEntry("tr_pdexp_trunk_a", "[TR] Trunk A")
    AddTextEntry("tr_pdexp_trunk_b", "[TR] Trunk B")
    AddTextEntry("tr_pdexp_trunk_c", "[TR] Trunk C")
    AddTextEntry("tr_pdexp_callsign_a0", "[TR] CallSign 0")
    AddTextEntry("tr_pdexp_callsign_a1", "[TR] CallSign 1")
    AddTextEntry("tr_pdexp_callsign_a2", "[TR] CallSign 2")
    AddTextEntry("tr_pdexp_callsign_a3", "[TR] CallSign 3")
    AddTextEntry("tr_pdexp_callsign_a4", "[TR] CallSign 4")
    AddTextEntry("tr_pdexp_callsign_a5", "[TR] CallSign 5")
    AddTextEntry("tr_pdexp_callsign_a6", "[TR] CallSign 6")
    AddTextEntry("tr_pdexp_callsign_a7", "[TR] CallSign 7")
    AddTextEntry("tr_pdexp_callsign_a8", "[TR] CallSign 8")
    AddTextEntry("tr_pdexp_callsign_a9", "[TR] CallSign 9")
    AddTextEntry("tr_pdexp_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_pdexp_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_pdexp_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_pdexp_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_pdexp_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_pdexp_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_pdexp_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_pdexp_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_pdexp_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_pdexp_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_pdexp_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_pdexp_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_pdexp_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_pdexp_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_pdexp_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_pdexp_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_pdexp_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_pdexp_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_pdexp_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_pdexp_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_pdexp_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_pdexp_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_pdexp_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_pdexp_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_pdexp_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_pdexp_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_pdexp_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_pdexp_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_pdexp_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_pdexp_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_pdexp_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_pdexp_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_pdexp_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_pdexp_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_pdexp_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_pdexp_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_pdexp_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_pdexp_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_pdexp_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_pdexp_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("sticker_001", "[TR] Sticker 1")
    AddTextEntry("sticker_002", "[TR] Sticker 2")
    AddTextEntry("sticker_003", "[TR] Sticker 3")
    AddTextEntry("sticker_004", "[TR] Sticker 4")
    AddTextEntry("sticker_005", "[TR] Sticker 5")
    AddTextEntry("sticker_006", "[TR] Sticker 6")
    AddTextEntry("sticker_007", "[TR] Sticker 7")
    AddTextEntry("sticker_008", "[TR] Sticker 8")
    AddTextEntry("sticker_009", "[TR] Sticker 9")
    AddTextEntry("sticker_010", "[TR] Sticker 10")
    AddTextEntry("sticker_011", "[TR] Sticker 11")
    AddTextEntry("sticker_012", "[TR] Sticker 12")
    AddTextEntry("sticker_013", "[TR] Sticker 13")
    AddTextEntry("sticker_014", "[TR] Sticker 14")
    AddTextEntry("sticker_015", "[TR] Sticker 15")
    AddTextEntry("sticker_016", "[TR] Sticker 16")
    AddTextEntry("sticker_017", "[TR] Sticker 17")
    AddTextEntry("sticker_018", "[TR] Sticker 18")
    AddTextEntry("sticker_019", "[TR] Sticker 19")
    AddTextEntry("sticker_020", "[TR] Sticker 20")
    AddTextEntry("sticker_021", "[TR] Sticker 21")
    AddTextEntry("sticker_022", "[TR] Sticker 22")
    AddTextEntry("sticker_023", "[TR] Sticker 23")
    AddTextEntry("sticker_024", "[TR] Sticker 24")
    AddTextEntry("sticker_025", "[TR] Sticker 25")
    AddTextEntry("sticker_026", "[TR] Sticker 26")
    AddTextEntry("sticker_027", "[TR] Sticker 27")
    AddTextEntry("sticker_028", "[TR] Sticker 28")
    AddTextEntry("sticker_029", "[TR] Sticker 29")
    AddTextEntry("sticker_030", "[TR] Sticker 30")
    AddTextEntry("sticker_031", "[TR] Sticker 31")
    AddTextEntry("sticker_032", "[TR] Sticker 32")
    AddTextEntry("sticker_033", "[TR] Sticker 33")
    AddTextEntry("sticker_034", "[TR] Sticker 34")
    AddTextEntry("sticker_035", "[TR] Sticker 35")
    AddTextEntry("sticker_036", "[TR] Sticker 36")
    AddTextEntry("sticker_037", "[TR] Sticker 37")
    AddTextEntry("sticker_038", "[TR] Sticker 38")
    AddTextEntry("sticker_039", "[TR] Sticker 39")
    AddTextEntry("sticker_040", "[TR] Sticker 40")
    AddTextEntry("sticker_041", "[TR] Sticker 41")
    AddTextEntry("sticker_042", "[TR] Sticker 42")
    AddTextEntry("sticker_043", "[TR] Sticker 43")
    AddTextEntry("sticker_044", "[TR] Sticker 44")
    AddTextEntry("sticker_045", "[TR] Sticker 45")
    AddTextEntry("sticker_046", "[TR] Sticker 46")
    AddTextEntry("sticker_047", "[TR] Sticker 47")
    AddTextEntry("sticker_048", "[TR] Sticker 48")
    AddTextEntry("sticker_049", "[TR] Sticker 49")
    AddTextEntry("sticker_050", "[TR] Sticker 50")
    AddTextEntry("tr_pdexp_ant_1a", "[TR] Local Range")
    AddTextEntry("tr_pdexp_ant_2a", "[TR] County Range")
    AddTextEntry("tr_pdexp_ant_1b", "[TR] State Range")
    AddTextEntry("tr_pdexp_livery_1", "[TR] LSPD Livery")
    AddTextEntry("tr_pdexp_livery_2", "[TR] LSPD K9 Livery")
    AddTextEntry("tr_pdexp_livery_3", "[TR] Sheriff Livery")
    AddTextEntry("tr_pdexp_livery_4", "[TR] Sheriff K9 Livery")
    AddTextEntry("tr_pdexp_livery_5", "[TR] State Livery")
    AddTextEntry("tr_pdexp_livery_6", "[TR] State K9 Livery")
    AddTextEntry("tr_pdexp_livery_7", "[TR] Ranger Livery")
    AddTextEntry("tr_pdexp_livery_8", "[TR] Ranger K9 Livery")
    AddTextEntry("tr_pdexp_livery_9", "[TR] Blank")
    AddTextEntry("tr_pdexp_livery_10", "[TR] Blank")
    AddTextEntry("tr_pdexp_rank_1a", "[TR] Supv")
    AddTextEntry("tr_pdexp_rank_1b", "[TR] Command.")
end)
